# Generated by Django 5.2 on 2025-05-06 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('saving_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.groupmember')),
            ],
            options={
                'unique_together': {('month', 'member')},
            },
        ),
        migrations.CreateModel(
            name='DepositedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('amount_deposited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('related_month', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='deposit_images/')),
                ('records', models.ManyToManyField(blank=True, to='saving.record')),
            ],
        ),
    ]
