# Generated by Django 5.2 on 2025-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositedby',
            name='records',
            field=models.ManyToManyField(blank=True, to='saving.record'),
        ),
    ]
