# Generated by Django 5.2 on 2025-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0002_depositedby_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grand Total',
                'verbose_name_plural': 'Grand Total',
            },
        ),
    ]
