# Generated by Django 5.2 on 2025-05-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0003_grandtotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrandTotal',
        ),
    ]
